### ISSUE TITLE
Torch.distributed.elastic.multiprocessing.api.SignalException: Process XXXX got signal :1

### ISSUE THREAD

**Issue by timerobin** [JingyunLiang/VRT#47]
Hello, thank you for the code.
I meet an error when I train with 005_train_vrt_videodeblurring_dvd.json

`Fix keys: ['spynet', 'deform'] for the first 20000 iters.
Fix keys: ['spynet', 'deform'] for the first 20000 iters.
22-09-01 02:31:11.512 : <epoch:  0, iter:     400, lr:4.000e-04> G_loss: 7.544e-02 
22-09-01 02:48:36.264 : <epoch:  0, iter:     600, lr:4.000e-04> G_loss: 1.637e-02 
22-09-01 03:06:01.631 : <epoch:  0, iter:     800, lr:4.000e-04> G_loss: 7.941e-02 
WARNING:torch.distributed.elastic.agent.server.api:Received 1 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2704351 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2704352 closing signal SIGHUP
Traceback (most recent call last):
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 236, in launch_agent
    result = agent.run()
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/ET/huiyuxiang/miniconda3/envs/deblur/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 2704341 got signal: 1`

and I use the python=3.7.13, pytorch=1.12.1

**Comment by timerobin** [comment]
it's something wrong about nohup, and should use tmux or screen
